from .circle_boundary import CircleBoundaryLoss
from .collection import ConformalCollectionLoss
from .collection import IsometricCollectionLoss
from .inter_map import ConformalMapLoss
from .inter_map import IsometricMapLoss
from .parametrization import ConformalParamLoss
from .parametrization import IsometricParamLoss
from .sdf import SDFLoss
from .ssd import SSDLoss
